/// <reference types="Cypress" />

describe('Add Product to Cart to Reach Checkout Page', function () {
    //Test Case 1
    it(`Proceed to Checkout after Adding 1x Product from Home Page`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1')   
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '1')
    })

    //Test Case 2
    it(`Proceed to Checkout via Cart Page after adding 1x Product from Home Page`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1')   
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-cart > span').contains('View Cart').click({force: true})
        cy.get('#MainContent > div > div.cart-container > div:nth-child(1)').should('have.length', '1')
        cy.get('#Quantity--0').should('have.attr', 'value', '1')
        cy.wait(2000)
        cy.get('#MainContent > div > div > div:nth-child(4) > div.checkout-btns > div.checkout-btn > a').click()
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '1')
    })

    //Test Case 3
    it(`Proceed to Checkout after adding 2x Products from Home Page`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1') 
        cy.wait(2000)
        cy.get('.product-loop > div.column:nth-child(4) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.wait(2000)
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '2')
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')   
    })

    //Test Case 4
    it(`Proceed to Checkout via Cart Page after adding 2x Products from Home Page`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1') 
        cy.wait(2000)
        cy.get('.product-loop > div.column:nth-child(4) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.wait(2000)
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '2')
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-cart > span').contains('View Cart').click({force: true})
        cy.wait(2000)
        cy.get('#MainContent > div > div.cart-container > div:nth-child(1)').should('have.length', '1')
        cy.get('#Quantity--0').should('have.attr', 'value', '1')
        cy.get('#MainContent > div > div.cart-container > div:nth-child(2)').should('have.length', '1')
        cy.get('#Quantity--1').should('have.attr', 'value', '1')
        cy.wait(2000)
        cy.get('#MainContent > div > div > div:nth-child(4) > div.checkout-btns > div.checkout-btn > a').click()
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')     
    })
    
    //Test Case 5
    it(`Proceed to Checkout after Adding 1x Product from Product Tile and 1x Product from PDP to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1') 
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > a.product-tile > div.product-tile__inner-container.banner-active').click({force: true})
        cy.get('#AddToCart-inpage > span#AddToCartText-').contains('Add to Cart').click()
        cy.wait(2000)
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '2')
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')   
    })

    //Test Case 6
    it(`Proceed to Checkout via Cart Page after Adding 1x Product from Product Tile and 1x Product from PDP to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1') 
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > a.product-tile > div.product-tile__inner-container.banner-active').click({force: true})
        cy.get('#AddToCart-inpage > span#AddToCartText-').contains('Add to Cart').click()
        cy.wait(2000)
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '2')
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-cart > span').contains('View Cart').click({force: true})
        cy.wait(2000)
        cy.get('#MainContent > div > div.cart-container > div:nth-child(1)').should('have.length', '1')
        cy.get('#Quantity--0').should('have.attr', 'value', '1')
        cy.get('#MainContent > div > div.cart-container > div:nth-child(2)').should('have.length', '1')
        cy.get('#Quantity--1').should('have.attr', 'value', '1')
        cy.wait(2000)
        cy.get('#MainContent > div > div > div:nth-child(4) > div.checkout-btns > div.checkout-btn > a').click()
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')     
    })

    //Test Case 7
    it(`Proceed to Checkout after Adding 1x Product from Search`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#quicksearch-search-box > div > input').type('apple')
        cy.get('#quicksearch-search-results > div > div.ais-infinite-hits.ais-results-as-block > div:nth-child(2) > div > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1')    
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '1')
    })

    //Test Case 8
    it(`Proceed to Checkout via Cart Page after Adding 1x Product from Search`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#quicksearch-search-box > div > input').type('apple')
        cy.get('#quicksearch-search-results > div > div.ais-infinite-hits.ais-results-as-block > div:nth-child(2) > div > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.wait(2000)
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1')
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-cart > span').contains('View Cart').click({force: true})
        cy.wait(2000)
        cy.get('#MainContent > div > div.cart-container > div:nth-child(1)').should('have.length', '1')
        cy.get('#Quantity--0').should('have.attr', 'value', '1')
        cy.wait(2000)
        cy.get('#MainContent > div > div > div:nth-child(4) > div.checkout-btns > div.checkout-btn > a').click()
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '1')     
    })

    //Test Case 9
    it(`Proceed to Checkout after Adding 2x Products from Search`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#quicksearch-search-box > div > input').type('apple')
        cy.get('#quicksearch-search-results > div > div.ais-infinite-hits.ais-results-as-block > div:nth-child(2) > div > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1')
        cy.get('#quicksearch-search-box > div > input').clear()
        cy.get('#quicksearch-search-box > div > input').type('samsung')
        cy.wait(2000)
        cy.get('#quicksearch-search-results > div > div.ais-infinite-hits.ais-results-as-block > div:nth-child(2) > div > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '2')  
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')
    })

    //Test Case 10
    it(`Proceed to Checkout via Cart Page after Adding 2x Products from Search`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#quicksearch-search-box > div > input').type('apple')
        cy.get('#quicksearch-search-results > div > div.ais-infinite-hits.ais-results-as-block > div:nth-child(2) > div > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1')
        cy.get('#quicksearch-search-box > div > input').clear()
        cy.get('#quicksearch-search-box > div > input').type('samsung')
        cy.wait(2000)
        cy.get('#quicksearch-search-results > div > div.ais-infinite-hits.ais-results-as-block > div:nth-child(2) > div > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '2')
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-cart > span').contains('View Cart').click({force: true})
        cy.wait(2000)
        cy.get('#MainContent > div > div.cart-container > div:nth-child(1)').should('have.length', '1')
        cy.get('#Quantity--0').should('have.attr', 'value', '1')
        cy.get('#MainContent > div > div.cart-container > div:nth-child(2)').should('have.length', '1')
        cy.get('#Quantity--1').should('have.attr', 'value', '1') 
        cy.wait(2000)
        cy.get('#MainContent > div > div > div:nth-child(4) > div.checkout-btns > div.checkout-btn > a').click()
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')     
    })

    //Test Case 11
    it(`Proceed to Checkout after Adding 1x Product from Collection Page to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#top-menu > li:nth-child(2)').click()
        cy.get('#collection-search-results > div > div.ais-hits--item.ais-hits--item:nth-child(3) > div.ais-hit.ais-product.product-tile__container > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '1') 
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '1')
    })

    //Test Case 12
    it(`Proceed to Checkout via Cart Page after Adding 1x Product from Collection Page to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#top-menu > li:nth-child(2)').click()
        cy.get('#collection-search-results > div > div.ais-hits--item.ais-hits--item:nth-child(3) > div.ais-hit.ais-product.product-tile__container > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '1')
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-cart > span').contains('View Cart').click({force: true})
        cy.get('#MainContent > div > div.cart-container > div:nth-child(1)').should('have.length', '1')
        cy.get('#Quantity--0').should('have.attr', 'value', '1')
        cy.wait(2000)
        cy.get('#MainContent > div > div > div:nth-child(4) > div.checkout-btns > div.checkout-btn > a').click()
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '1')     
    })

    //Test Case 13
    it(`Proceed to Checkout after Adding 2x Products from Collection Page to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#top-menu > li:nth-child(2)').click()
        cy.get('#collection-search-results > div > div.ais-hits--item.ais-hits--item:nth-child(3) > div.ais-hit.ais-product.product-tile__container > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '1')
        cy.wait(2000)
        cy.get('#collection-search-results > div > div.ais-hits--item.ais-hits--item:nth-child(5) > div.ais-hit.ais-product.product-tile__container > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '2')  
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')
    })

    //Test Case 14
    it(`Proceed to Checkout via Cart Page after Adding 2x Products from Collection Page to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.get('#top-menu > li:nth-child(2)').click()
        cy.get('#collection-search-results > div > div.ais-hits--item.ais-hits--item:nth-child(3) > div.ais-hit.ais-product.product-tile__container > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '1')
        cy.wait(2000)
        cy.get('#collection-search-results > div > div.ais-hits--item.ais-hits--item:nth-child(5) > div.ais-hit.ais-product.product-tile__container > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '2')  
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-cart > span').contains('View Cart').click({force: true})
        cy.get('#MainContent > div > div.cart-container > div:nth-child(1)').should('have.length', '1')
        cy.get('#Quantity--0').should('have.attr', 'value', '1')
        cy.get('#MainContent > div > div.cart-container > div:nth-child(2)').should('have.length', '1')
        cy.get('#Quantity--1').should('have.attr', 'value', '1')
        cy.wait(2000)
        cy.get('#MainContent > div > div > div:nth-child(4) > div.checkout-btns > div.checkout-btn > a').click()
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '2')     
    })

    //Test Case 15
    it(`Proceed to Checkout after Adding 1x (HomePage) | 1x (PDP) | 1x (Search) | 1x (CollectionPage) to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()

        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > .product-tile__cta.product-tile__cta--simple > form')
          .find('button.cart-button__add > span > span.button-text').contains('Add to Cart').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '1')
          
        cy.get('.product-loop > div.column:nth-child(3) > .product-tile__container > a.product-tile > div.product-tile__inner-container.banner-active').click({force: true})
        cy.get('#AddToCart-inpage > span#AddToCartText-').contains('Add to Cart').click()
        cy.wait(2000)
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '2')  

        cy.get('#quicksearch-search-box > div > input').type('apple')
        cy.get('#quicksearch-search-results > div > div.ais-infinite-hits.ais-results-as-block > div:nth-child(2) > div > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
          .find('#cart-count').should('have.text', '3')    
        cy.get('.ais-clear-all--link').click()

        cy.get('#top-menu > li:nth-child(2)').click()
        cy.get('#collection-search-results > div > div.ais-hits--item.ais-hits--item:nth-child(3) > div.ais-hit.ais-product.product-tile__container > div.ais-hit--cart.product-tile__cta > button').click({force: true})
        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle')
        cy.get('#cart-count').should('have.text', '4') 

        cy.get('#shopify-section-header > header > div.site-header-container.utilities > div.utility-link.mobile-order-7 > #minicart-toggle').click()
        cy.get('#mini-cart > div > form > div.cart-buttons > button.collect-checkout.cart-buttons-checkout > span').contains('Checkout').click({force: true})  
        cy.get('#order-summary > div > div.order-summary__section.order-summary__section--product-list.cart > div > table > tbody > tr.product').should('have.length', '4')
    })
}); //End of Describe
  

