describe('Add Product to Cart to Reach Checkout Page', function () {
    //Test Case 1
    it(`Proceed to Checkout after Adding 1x Product from Home Page`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.Add1xProductFromHomepage()
        cy.NavigateToCartIconQty()
          .should('have.text', '1')   
        cy.NavigateToCheckoutPagefromCartIcon()  
        cy.NavigateToProductLineItemSection()
          .should('have.length', '1')
    })

    //Test Case 2
    it(`Proceed to Checkout via Cart Page after adding 1x Product from Home Page`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.Add1xProductFromHomepage()
        cy.NavigateToCartIconQty()
          .should('have.text', '1')   
        cy.NavigateToCartPagefromCartIcon()
        cy.NavigateToCartPageProductSummarySectionOne()
          .should('have.length', '1')
        cy.NavigateToCartPageProductSummarySectionLineItemOne()
          .should('have.attr', 'value', '1')
        cy.wait(2000)
        cy.NavigateToCheckoutPagefromCartPage()
        cy.NavigateToProductLineItemSection()
          .should('have.length', '1')
    })

    //Test Case 3
    it(`Proceed to Checkout after adding 2x Products from Home Page`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.Add1xProductFromHomepage()
        cy.NavigateToCartIconQty()
          .should('have.text', '1') 
        cy.wait(2000)
        cy.AddAnother1xProductFromHomepage()
        cy.wait(2000)
        cy.NavigateToCartIconQty()
          .should('have.text', '2')
        cy.NavigateToCheckoutPagefromCartIcon() 
        cy.NavigateToProductLineItemSection() 
          .should('have.length', '2')   
    })

    //Test Case 4
    it(`Proceed to Checkout via Cart Page after adding 2x Products from Home Page`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.Add1xProductFromHomepage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
      cy.wait(2000)  
      cy.AddAnother1xProductFromHomepage()
      cy.wait(2000)
      cy.NavigateToCartIconQty()
        .should('have.text', '2')
      cy.NavigateToCartPagefromCartIcon()
      cy.wait(2000)
      cy.NavigateToCartPageProductSummarySectionOne()
        .should('have.length', '1')
        cy.NavigateToCartPageProductSummarySectionLineItemOne()
        .should('have.attr', 'value', '1')
      cy.NavigateToCartPageProductSummarySectionTwo()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemTwo()
        .should('have.attr', 'value', '1')
      cy.wait(2000)
      cy.NavigateToCheckoutPagefromCartPage()
      cy.NavigateToProductLineItemSection()
        .should('have.length', '2')     
    })

    //Test Case 5
    it(`Proceed to Checkout after Adding 1x Product from Product Tile and 1x Product from PDP to Cart`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.Add1xProductFromHomepage()
        cy.NavigateToCartIconQty()
          .should('have.text', '1') 
        cy.Add1xProductFromPDP()
        cy.wait(2000)
        cy.NavigateToCartIconQty()
          .should('have.text', '2')
        cy.NavigateToCheckoutPagefromCartIcon()
        cy.NavigateToProductLineItemSection()
          .should('have.length', '2')   
    })

    //Test Case 6
    it(`Proceed to Checkout via Cart Page after Adding 1x Product from Product Tile and 1x Product from PDP to Cart`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.Add1xProductFromHomepage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1') 
      cy.Add1xProductFromPDP()
      cy.wait(2000)
      cy.NavigateToCartIconQty()
        .should('have.text', '2')
      cy.NavigateToCartPagefromCartIcon()
      cy.wait(2000)
      cy.NavigateToCartPageProductSummarySectionOne()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemOne()
        .should('have.attr', 'value', '1')
      cy.NavigateToCartPageProductSummarySectionTwo()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemTwo()
        .should('have.attr', 'value', '1')
      cy.wait(2000)
      cy.NavigateToCheckoutPagefromCartPage()
      cy.NavigateToProductLineItemSection()
        .should('have.length', '2')     
    })

    //Test Case 7
    it(`Proceed to Checkout after Adding 1x Product from Search`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.SearchFirstProduct()
        cy.AddProductFromSearchToCart()
        cy.NavigateToCartIconQty()
          .should('have.text', '1')    
        cy.NavigateToCheckoutPagefromCartIcon() 
        cy.NavigateToProductLineItemSection()
          .should('have.length', '1')
    })

    //Test Case 8
    it(`Proceed to Checkout via Cart Page after Adding 1x Product from Search`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.SearchFirstProduct()
      cy.AddProductFromSearchToCart()
      cy.wait(2000)
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
      cy.NavigateToCartPagefromCartIcon()
      cy.wait(2000)
      cy.NavigateToCartPageProductSummarySectionOne()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemOne()
        .should('have.attr', 'value', '1')
      cy.wait(2000)
      cy.NavigateToCheckoutPagefromCartPage()
      cy.NavigateToProductLineItemSection()
        .should('have.length', '1')     
    })

    //Test Case 9
    it(`Proceed to Checkout after Adding 2x Products from Search`, function() {
        cy.LoginUATShopify() 
        cy.LaunchDesktopScreenSize()
        cy.SearchFirstProduct()
        cy.AddProductFromSearchToCart()
        cy.NavigateToCartIconQty()
          .should('have.text', '1')
        cy.ClearSearchInput()
        cy.SearchSecondProduct()
        cy.wait(2000)
        cy.AddProductFromSearchToCart()
        cy.NavigateToCartIconQty()
          .should('have.text', '2')  
        cy.NavigateToCheckoutPagefromCartIcon() 
        cy.NavigateToProductLineItemSection()
          .should('have.length', '2')
    })

    //Test Case 10
    it(`Proceed to Checkout via Cart Page after Adding 2x Products from Search`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.SearchFirstProduct()
      cy.AddProductFromSearchToCart()
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
      cy.ClearSearchInput()
      cy.SearchSecondProduct()
      cy.wait(2000)
      cy.AddProductFromSearchToCart()
      cy.NavigateToCartIconQty()
        .should('have.text', '2')
      cy.NavigateToCartPagefromCartIcon()
      cy.wait(2000)
      cy.NavigateToCartPageProductSummarySectionOne()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemOne()
        .should('have.attr', 'value', '1')
      cy.NavigateToCartPageProductSummarySectionTwo()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemTwo()
        .should('have.attr', 'value', '1') 
      cy.wait(2000)
      v
        .should('have.length', '2')     
    })

    //Test Case 11
    it(`Proceed to Checkout after Adding 1x Product from Collection Page to Cart`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.NavigateToCollectionPage()
      cy.Add1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1') 
      cy.NavigateToCheckoutPagefromCartIcon() 
      cy.NavigateToProductLineItemSection()
        .should('have.length', '1')
    })

    //Test Case 12
    it(`Proceed to Checkout via Cart Page after Adding 1x Product from Collection Page to Cart`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.NavigateToCollectionPage()
      cy.Add1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
      cy.NavigateToCartPagefromCartIcon()
      cy.NavigateToCartPageProductSummarySectionOne()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemOne()
        .should('have.attr', 'value', '1')
      cy.wait(2000)
      cy.NavigateToCheckoutPagefromCartPage()
      cy.NavigateToProductLineItemSection()
        .should('have.length', '1')     
    })  

    //Test Case 13
    it(`Proceed to Checkout after Adding 2x Products from Collection Page to Cart`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.NavigateToCollectionPage()
      cy.Add1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
      cy.wait(2000)
      cy.AddAnother1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '2')  
      cy.NavigateToCheckoutPagefromCartIcon() 
      cy.NavigateToProductLineItemSection().should('have.length', '2')
    })

    //Test Case 14
    it(`Proceed to Checkout via Cart Page after Adding 2x Products from Collection Page to Cart`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()
      cy.NavigateToCollectionPage()
      cy.Add1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
      cy.wait(2000)
      cy.AddAnother1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '2')  
      cy.NavigateToCartPagefromCartIcon()      
      cy.NavigateToCartPageProductSummarySectionOne()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemOne()
        .should('have.attr', 'value', '1')
      cy.NavigateToCartPageProductSummarySectionTwo()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemTwo()
        .should('have.attr', 'value', '1')
      cy.wait(2000)
      cy.NavigateToCheckoutPagefromCartPage()
      cy.NavigateToProductLineItemSection()
        .should('have.length', '2')     
    })

    //Test Case 15
    it(`Proceed to Checkout after Adding 1x (HomePage) | 1x (PDP) | 1x (Search) | 1x (CollectionPage) to Cart`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()

      cy.Add1xProductFromHomepage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
        
      cy.Add1xProductFromPDP()
      cy.wait(2000)
      cy.NavigateToCartIconQty()
        .should('have.text', '2')  

      cy.SearchFirstProduct()
      cy.AddProductFromSearchToCart()
      cy.NavigateToCartIconQty()
        .should('have.text', '3')    
      cy.CloseSearchPage()

      cy.NavigateToCollectionPage()
      cy.Add1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '4') 

      cy.NavigateToCheckoutPagefromCartIcon() 
      cy.NavigateToProductLineItemSection()
        .should('have.length', '4')
    })

    //Test Case 16
    it(`Proceed to Checkout via Cart Page after Adding 1x (HomePage) | 1x (PDP) | 1x (Search) | 1x (CollectionPage) to Cart`, function() {
      cy.LoginUATShopify() 
      cy.LaunchDesktopScreenSize()

      cy.Add1xProductFromHomepage()
      cy.NavigateToCartIconQty()
        .should('have.text', '1')
        
      cy.Add1xProductFromPDP()
      cy.wait(2000)
      cy.NavigateToCartIconQty()
        .should('have.text', '2')  

      cy.SearchFirstProduct()
      cy.AddProductFromSearchToCart()
      cy.NavigateToCartIconQty()
        .should('have.text', '3')    
      cy.CloseSearchPage()

      cy.NavigateToCollectionPage()
      cy.Add1xProductFromCollectionPage()
      cy.NavigateToCartIconQty()
        .should('have.text', '4') 

      cy.NavigateToCartPagefromCartIcon()      
      cy.NavigateToCartPageProductSummarySectionOne()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemOne()
        .should('have.attr', 'value', '1')
      cy.NavigateToCartPageProductSummarySectionTwo()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemTwo()
        .should('have.attr', 'value', '1')
      cy.NavigateToCartPageProductSummarySectionThree()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemThree()
        .should('have.attr', 'value', '1')
      cy.NavigateToCartPageProductSummarySectionFour()
        .should('have.length', '1')
      cy.NavigateToCartPageProductSummarySectionLineItemFour()
        .should('have.attr', 'value', '1')
  
      cy.wait(2000)

      cy.NavigateToCheckoutPagefromCartPage()
      cy.NavigateToProductLineItemSection()
        .should('have.length', '4')     
    })
}); //End of Describe
  

